#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "markdown-it-py[linkify]>=3.0",
#   "mdit-py-plugins>=0.4",
#   "Pygments>=2.18",
# ]
# ///
"""
build.py — generates `docs/index.html` from the repository READMEs.

A single, self-contained page: no CDN, no external asset, no server.
The markdown is converted at build time (markdown-it-py, CommonMark + tables) and
highlighted by Pygments; the embedded JS only handles navigation, search, language,
theme and the copy buttons.

Usage:
    ./docs/build.py                  # uv installs the deps on the fly (PEP 723)
    uv run docs/build.py --out /tmp/doc.html
    uv run docs/build.py --strict    # fails when an internal link does not resolve
    make docs

BILINGUAL: every page exists in two versions, in the SAME directory — English
carries the canonical name (`README.md`, `CLAUDE.md`, `UPGRADE.md`), French its
mirror (`LISEZ-MOI.md`, `MISE-A-JOUR.md`), see MIRRORS. English is the default
language; the EN/FR selector of the side bar switches the whole site and the URL
(`#fr/kubeadm-upgrade`).

ADDING A PAGE: nothing to do, every `*.md` of the repository is discovered
automatically. Only the menu grouping and the emoji come from GROUPS / EMOJIS
below; an unknown directory falls into "Other".
"""

from __future__ import annotations

import argparse
import base64
import html
import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

from markdown_it import MarkdownIt
from markdown_it.token import Token
from mdit_py_plugins.anchors import anchors_plugin
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import get_lexer_by_name
from pygments.util import ClassNotFound

ROOT = Path(__file__).resolve().parent.parent

# Directories never explored (dependencies, artifacts, generator output).
# `_k8s` is a SUBMODULE (the k8s-playground repo): its documentation is built and
# published by THAT repo, not by this one. Including it here would produce two diverging
# copies of the same doc, and would break the CI build, where the submodule is not
# necessarily checked out (the directory is empty there). An external link replaces it
# in the menu.
EXCLUDED = {".git", ".vagrant", ".terraform", "node_modules", "docs", "iso", "_out", "_k8s"}

# Pages published EVEN when git ignores them. Deliberately EMPTY: the page is published
# on GitHub Pages, where the build only has the versioned files. Forcing a local
# directory in here would produce a local page different from the published one, and
# could expose a private configuration (real domain, application keys).
# An addon that must appear in the docs therefore has to be versioned.
FORCED: set[str] = set()

# --- Languages --------------------------------------------------------------
# Name of the English (canonical) file -> name of its French mirror, same directory.
MIRRORS = {
    "README.md":          "LISEZ-MOI.md",
    "UPGRADE.md":         "MISE-A-JOUR.md",
    "TROUBLESHOOTING.md": "DEPANNAGE.md",
}

# ENGLISH-ONLY pages by choice: no French mirror, and therefore no "not translated
# yet" badge — that would flag an oversight where there is a decision.
# CLAUDE.md addresses coding agents, whose working language is English.
WITHOUT_MIRROR = {"CLAUDE.md"}
LANGUAGES = ("en", "fr")
DEFAULT_LANGUAGE = "en"

# The project's public repository, pinned here rather than in the HTML template: it is
# the page's only external URL, and the reader of an offline copy must be able to find
# the source again. The pictogram is an INLINE SVG (see repo_link): the page is
# self-contained, so no shields.io badge and no icon served by a CDN.
REPO_URL = "https://github.com/OPS-NC/Vagrant-kubeadm"

# Documentation of the application layer. It lives in the k8s-playground repo, mounted
# here as a submodule on `_k8s/` and shared with the Talos lab: a single source for both,
# hence a single place to maintain it.
PLATFORM_URL = "https://ops-nc.github.io/k8s-playground/"

# That site is generated by THIS script, so it answers the same `#<lang>/<page>` routes.
# `readme` is the route id of its home page (derived from `README.md`), which lets the
# sidebar link carry the language being read: a French reader lands on the French page
# instead of the site's default (or whatever language it last remembered).
PLATFORM_HOME = "readme"


def platform_href(lang: str) -> str:
    """URL of the application layer's documentation, in the given language."""
    return f"{PLATFORM_URL}#{lang}/{PLATFORM_HOME}"

# The "English · Français" banner placed at the top of every file for GitHub
# readers. The HTML page has its own selector, so we strip it.
RE_BANNER = re.compile(r"<!--\s*i18n\s*-->.*?<!--\s*/i18n\s*-->\s*", re.DOTALL)

# Interface labels. Every visible string of the template goes through here.
LABELS: dict[str, dict[str, str]] = {
    "en": {
        "search":       "Search…   /",
        "search_aria":  "Search a page",
        "toc":        "On this page",
        "copy":              "Copy",
        "copied":           "Copied!",
        "failed":           "Failed",
        "to_light":      "Switch to light theme",
        "to_dark":     "Switch to dark theme",
        "theme_aria":      "Documentation theme",
        "theme_light":     "Light",
        "theme_dark":    "Dark",
        "menu":            "Open the menu",
        "lang_aria":     "Documentation language",
        "source":          "Source:",
        "sections":        "sections",
        "badge":           "untracked",
        "badge_title":     "Not in git: local directory",
        "badge_lang":    "EN",
        "badge_lang_title": "Not translated yet — English page shown",
        "repo":           "GitHub repository",
        "platform":      "Application layer (k8s-playground)",
        "platform_short": "Platform",
        "subtitle":      "Kubernetes lab built with kubeadm on VirtualBox, driven by Vagrant.",
    },
    "fr": {
        "search":       "Rechercher…   /",
        "search_aria":  "Rechercher une page",
        "toc":        "Sur cette page",
        "copy":              "Copier",
        "copied":           "Copié !",
        "failed":           "Échec",
        "to_light":      "Passer en clair",
        "to_dark":     "Passer en sombre",
        "theme_aria":      "Thème de la documentation",
        "theme_light":     "Clair",
        "theme_dark":    "Sombre",
        "menu":            "Ouvrir le menu",
        "lang_aria":     "Langue de la documentation",
        "source":          "Source :",
        "sections":        "sections",
        "badge":           "non commité",
        "badge_title":     "Absent de git : dossier local",
        "badge_lang":    "EN",
        "badge_lang_title": "Pas encore traduit — page anglaise affichée",
        "repo":           "Dépôt GitHub",
        "platform":      "Couche applicative (k8s-playground)",
        "platform_short": "Plateforme",
        "subtitle":      "Lab Kubernetes monté avec kubeadm sur VirtualBox, piloté par Vagrant.",
    },
}

# --- Menu layout ------------------------------------------------------------
# (headings per language, emoji, ENGLISH paths or directories, in display order)
GROUPS: list[tuple[dict[str, str], str, list[str]]] = [
    ({"en": "The lab",  "fr": "Le lab"}, "🏠",
     ["README.md", "kubeadm/UPGRADE.md", "TROUBLESHOOTING.md"]),
    # The Network / Storage / Secrets / Observability / Security / Demos groups were
    # removed when `_k8s/` became a submodule: those pages belong to the k8s-playground
    # repo, which publishes its own documentation (see PLATFORM_URL).
    ({"en": "AI agent", "fr": "Agent IA"}, "🤖", ["CLAUDE.md"]),
]
OTHER = {"en": "Other", "fr": "Autres"}

EMOJIS: dict[str, str] = {
    "README.md":            "🏠",
    "CLAUDE.md":            "🤖",
    "TROUBLESHOOTING.md":   "🚑",
    "kubeadm/UPGRADE.md":   "⬆️",
}

# Callouts: a marker at the start of a blockquote picks the colour. Both languages
# share the table, hence the FR *and* EN markers.
CALLOUTS: list[tuple[str, tuple[str, ...]]] = [
    ("danger", ("⚠️", "🚨", "❌", "attention", "danger", "jamais", "ne pas", "ne jamais",
                "never", "do not", "don't", "warning")),
    ("tip",    ("💡", "✅", "🎯", "astuce", "conseil", "bon à savoir",
                "tip", "good to know")),
    ("info",   ("ℹ️", "📌", "📝", "🔍", "nb ", "nb :", "note", "remarque", "réf",
                "ref", "reminder")),
]


# ===========================================================================
#  Page discovery
# ===========================================================================

def git(*args: str) -> str:
    """Calls git in the repository; empty string when git is missing or errors out."""
    try:
        return subprocess.run(["git", "-C", str(ROOT), *args],
                              capture_output=True, text=True, check=True).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def ignores(paths: list[str]) -> set[str]:
    """Subset of the paths git ignores (e.g. the local proxmox/ project).

    We document the repository, not the local working directories — but a file that is
    merely *untracked* is still published, with a badge.
    """
    if not paths:
        return set()
    try:
        res = subprocess.run(["git", "-C", str(ROOT), "check-ignore", "--stdin"],
                             input="\n".join(paths), capture_output=True, text=True,
                             check=False)
        return set(res.stdout.split())      # rc=1 when nothing is ignored: normal
    except FileNotFoundError:
        return set()


def read_file(path: str) -> str:
    """A page's text, with the language banner stripped."""
    return RE_BANNER.sub("", (ROOT / path).read_text(encoding="utf-8"), count=1).lstrip()


def discover() -> list[dict]:
    """Lists the repository documents (one entry per EN/FR pair), following GROUPS."""
    tracked_files = set(git("ls-files", "*.md").split())
    found = sorted(
        p.relative_to(ROOT).as_posix()
        for p in ROOT.rglob("*.md")
        if not (EXCLUDED & set(p.relative_to(ROOT).parts))
    )
    excluded = ignores(found) - FORCED
    remaining = [c for c in found if c not in excluded]

    # pairs every English page with its French mirror, which leaves the list:
    # it is not one more document, it is the other version of the same document.
    mirror_of: dict[str, str] = {}
    for path in list(remaining):
        p = Path(path)
        if p.name in MIRRORS:
            fr = (p.parent / MIRRORS[p.name]).as_posix()
            if fr in remaining:
                mirror_of[path] = fr
                remaining.remove(fr)

    docs: list[dict] = []

    def take(path: str, group: dict[str, str], default_emoji: str) -> None:
        remaining.remove(path)
        fr = mirror_of.get(path, path)      # without a mirror: FR falls back to EN
        docs.append({
            "path": path,                   # path canonique (anglais)
            "paths": {"en": path, "fr": fr},
            "group": group,
            "emoji": EMOJIS.get(path, default_emoji),
            # without git we cannot assert anything: we flag nothing
            "tracked": path in tracked_files or not tracked_files,
        })

    for group, emoji, entries in GROUPS:
        for entry in entries:
            if entry.endswith(".md"):
                if entry in remaining:
                    take(entry, group, emoji)
            else:  # un dossier : ses pages canoniques, la moins profonde d'abord
                for path in sorted((c for c in list(remaining)
                                      if c.startswith(entry + "/")
                                      and Path(c).name in MIRRORS),
                                     key=lambda c: (c.count("/"), c)):
                    take(path, group, emoji)

    for path in list(remaining):     # nothing disappears from the menu
        take(path, OTHER, "📄")
    return docs


# ===========================================================================
#  Markdown → HTML conversion
# ===========================================================================

# Emoji en tête de title : les README commencent par un emoji (contrat de style),
# et le générateur en ajoute un. Sans séparation, ils apparaîtraient en double.
# The repetition tolerates spaces, so a heading carrying several of them
# (`# 🏠 🐧 Vagrant-KubeADM`) keeps them all grouped in the header.
RE_LEADING_EMOJI = re.compile(
    r"^((?:[\U0001F000-\U0001FAFF←-⇿⌀-➿⬀-⯿]"
    r"[︎️‍]*[ \t]*)+)"
)


def split_emoji(title: str) -> tuple[str, str]:
    """Detaches the leading emoji (or emojis) of a heading: (emoji, rest)."""
    m = RE_LEADING_EMOJI.match(title)
    return (m.group(1).strip(), title[m.end():].lstrip()) if m else ("", title)


def strip_markdown(text: str) -> str:
    """Plain text of a heading (menu, tab, search): the markup is stripped."""
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\*\*([^*]*)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]*)\*", r"\1", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    return text.strip()


def anchor(title: str) -> str:
    """GitHub-style slug: lowercase, accents kept, punctuation and emoji removed.

    The repository headings start with an emoji (`## 🚑 7. Dépannage`): without the
    trailing `strip("-")`, the slug would inherit a leading dash.
    """
    slug = "".join(c for c in title.lower() if c.isalnum() or c in " -_")
    return re.sub(r"[\s-]+", "-", slug).strip("-_")


def create_converter() -> MarkdownIt:
    """CommonMark + tables + raw HTML (`<details>`) + anchors on the headings."""
    md = (
        MarkdownIt("commonmark", {"html": True, "linkify": True, "breaks": False})
        .enable(["table", "strikethrough"])
        .use(anchors_plugin, max_level=4, permalink=True, permalinkSymbol="#",
             permalinkSpace=False, slug_func=anchor)
    )
    md.add_render_rule("fence", _render_fence)
    return md


def _render_fence(self, tokens: list[Token], idx: int, options, env) -> str:
    """Code block: Pygments highlighting + copy button + language label.

    The button carries no label at build time: the JS sets it in the active language,
    otherwise switching FR/EN would leave "Copier" behind in the English page.
    """
    tok = tokens[idx]
    # `tok.info` is " " (and not "") when the block's closing fence carries a trailing
    # space — a string of spaces is TRUTHY, so the old `if tok.info` test passed, and
    # `"".split()[0]` raised an IndexError that killed the whole generation.
    # We split first and index second: no branch left to lie to us.
    parts = (tok.info or "").strip().split()
    language = parts[0].lower() if parts else ""
    try:
        body = highlight(tok.content, get_lexer_by_name(language or "text"),
                          HtmlFormatter(nowrap=True))
    except ClassNotFound:
        body = html.escape(tok.content, quote=False)
    label_text = {"bash": "shell", "sh": "shell", "yml": "yaml", "": "text"}.get(language, language)
    return (
        f'<figure class="code-block" data-language="{html.escape(label_text, quote=True)}">'
        f'<button class="copy-btn" type="button"></button>'
        f'<pre><code>{body}</code></pre></figure>'
    )


def callout_kind(text: str) -> str:
    """Picks a callout's style from the beginning of its text."""
    debut = text.lstrip().lower()[:48]
    for name, markers in CALLOUTS:
        if any(m in debut for m in markers):
            return name
    return "neutral"


def prepare(token_list: list[Token]) -> tuple[str | None, list[dict]]:
    """Annotates the tokens (callouts, scrollable tables) and collects the TOC.

    Returns (H1 heading, TOC); the H1 is removed from the body, it serves as the header.
    """
    h1_title: str | None = None
    toc: list[dict] = []

    for i, tok in enumerate(token_list):
        if tok.type == "blockquote_open":
            # the blockquote's first inline determines the callout colour
            rest = next((t for t in token_list[i + 1:i + 6] if t.type == "inline"), None)
            tok.attrJoin("class", f"callout callout-{callout_kind(rest.content if rest else '')}")

        elif tok.type == "heading_open":
            inline = token_list[i + 1]
            text = re.sub(r"\s*#\s*$", "", inline.content).strip()
            if tok.tag == "h1" and h1_title is None:
                h1_title = text
                # neutralises the H1: it is redisplayed in the page header
                tok.type, tok.tag, tok.hidden = "html_block", "", True
                tok.content = ""
                inline.children, inline.content = [], ""
                token_list[i + 2].hidden = True
            elif tok.tag in ("h2", "h3"):
                toc.append({"level": tok.tag, "title": text,
                                 "anchor": tok.attrGet("id") or ""})

    return h1_title, toc


def convert(md: MarkdownIt, page: dict) -> dict:
    """Renders a page and returns everything the template needs.

    The title comes in three forms: the emoji (detached from the H1), the formatted
    title (markdown `code` becomes a real <code>) and the raw title
    (menu, onglet, search).
    """
    token_list = md.parse(page["text"])
    raw_title, toc = prepare(token_list)
    body = md.renderer.render(token_list, md.options, {})

    # tables: wrapped so they can scroll horizontally on mobile
    body = body.replace("<table>", '<div class="table-scroll"><table>')
    body = body.replace("</table>", "</table></div>")
    # the anchors point at the internal route #<page>/<section>
    body = re.sub(r'(class="header-anchor" href=")#',
                   rf"\1#{page['id']}/", body)

    raw_title = raw_title or Path(page["path"]).parent.name or page["path"]
    emoji, raw_title = split_emoji(raw_title)
    return {
        "body": body,
        "toc": toc,
        # the README emoji wins; otherwise the one from the EMOJIS table / the group
        "emoji": emoji or page["emoji"],
        "title_html": md.renderInline(raw_title),
        "title_text": strip_markdown(raw_title),
    }


# ===========================================================================
#  Internal links: `foo/README.md#anchor` → route `#en/foo-readme/anchor`
# ===========================================================================

RE_MD_LINK = re.compile(r'href="([^":#?]+\.md)(#[^"]*)?"')
RE_HEADING_ID = re.compile(r'<h[1-6][^>]*\sid="([^"]+)"')


def resolve(rendered: dict, index: dict[str, dict[str, str]],
             anchors: dict[str, set[str]], warnings: list[str]) -> str:
    """Rewrites the body's `*.md` links into internal routes of the single page.

    Without this pass, `[cilium/](../cilium/README.md)` would stay a *file* link:
    clickable on GitHub, dead on GitHub Pages. The fragment is
    reconciled with the anchors actually generated on the target side — GitHub anchors
    keep the leading dash left by the heading emoji, ours do not.
    """
    base = Path(rendered["path"]).parent
    table = index[rendered["lang"]]

    def replace_md(m: re.Match[str]) -> str:
        # `Path(target)` is RELATIVE: `.resolve()` used to resolve it against the
        # process cwd and not against ROOT. So the guard tested one path while
        # `.resolve()` computed another, hence an UNCAUGHT `ValueError: not in the
        # subpath of` that crashed the whole generation — as soon as build.py was run
        # from a directory other than the root, or as soon as a link pointed outside the
        # repo (`../neighbour/README.md`), in which case `--strict` crashed instead of
        # cleanly reporting the broken link.
        # We resolve explicitly from ROOT, and only convert when the target stays inside
        # the repo. `unquote` keeps this consistent with the fragment handling below (an
        # accented file name arrives percent-encoded).
        target = (base / unquote(m.group(1))).as_posix()
        absolute = (ROOT / target).resolve()
        if absolute.is_relative_to(ROOT):
            target = absolute.relative_to(ROOT).as_posix()
        target_id = table.get(target)
        if not target_id:
            warnings.append(f"{rendered['path']} → {m.group(1)} (page absente de la doc)")
            return m.group(0)
        # markdown-it percent-encodes non-ASCII characters: French anchors
        # (`#-accès-distant-…`) arrive here as `%C3%A8`, to be decoded before comparing.
        frag = unquote((m.group(2) or "")[1:])
        if frag:
            for attempt in (frag, frag.strip("-_"), anchor(frag)):
                if attempt in anchors[target_id]:
                    frag = attempt
                    break
            else:
                warnings.append(f"{rendered['path']} → {m.group(1)}#{frag} (anchor inconnue)")
                frag = ""
        return f'href="#{target_id}{"/" + frag if frag else ""}"'

    return RE_MD_LINK.sub(replace_md, rendered["body"])


RE_IMG_SRC = re.compile(r'(<img\b[^>]*?\bsrc=")([^"]+)(")', re.IGNORECASE)
MIMES = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
         ".gif": "image/gif", ".svg": "image/svg+xml", ".webp": "image/webp"}


def inline_images(body: str, path: str, warnings: list[str]) -> str:
    """Converts the body's LOCAL images into base64 data: URIs.

    The path written in the markdown is relative to the source file, so it is right
    for GitHub only; it would not resolve from the single page, which lives elsewhere
    (`docs/index.html` locally, `_site/index.html` in CI). Rather than copying the
    files next to the output, we embed them: the page stays ONE self-contained file,
    portable and readable offline — the promise kept everywhere else in this generator.

    Corollary: keep the images LIGHT, they inflate the page by roughly 4/3 of their
    own weight (base64 overhead).
    """
    base = Path(path).parent

    def replace_md(m: re.Match[str]) -> str:
        src = m.group(2)
        if src.startswith(("http://", "https://", "data:", "//")):
            return m.group(0)                      # ressource externe : intacte
        file_path = (ROOT / base / unquote(src)).resolve()
        if not file_path.is_file():
            warnings.append(f"{path} → {src} (image introuvable)")
            return m.group(0)
        mime = MIMES.get(file_path.suffix.lower())
        if mime is None:
            warnings.append(f"{path} → {src} (unsupported image format)")
            return m.group(0)
        data = base64.b64encode(file_path.read_bytes()).decode("ascii")
        return f"{m.group(1)}data:{mime};base64,{data}{m.group(3)}"

    return RE_IMG_SRC.sub(replace_md, body)


# ===========================================================================
#  Stylesheet
# ===========================================================================

def css_pygments() -> str:
    """Pygments highlighting themes, aligned with the palette's own logic.

    Same rule as the CSS variables: DARK is the default, light only applies when the
    reader explicitly chose it. Without that, code blocks would stay highlighted in the
    light theme on a dark page.
    """
    def defs(style: str, selector: str) -> str:
        try:
            return HtmlFormatter(style=style).get_style_defs(selector)
        except ClassNotFound:
            return HtmlFormatter().get_style_defs(selector)

    dark = defs("github-dark", ':root:not([data-theme="light"]) .code-block pre')
    light = defs("friendly", ':root[data-theme="light"] .code-block pre')
    return (
        f"{dark}\n{light}\n"
        # the blocks' background comes from our variables, not from the Pygments theme
        ".code-block pre{background:none!important}\n"
    )


DARK_PALETTE = """
  --bg:#15161a; --bg-2:#1c1e23; --bg-3:#24272d;
  --text:#e9eaec; --text-2:#a5a9b2; --text-3:#7a7f88;
  --border:#2b2e35; --border-strong:#3a3e46;
  --accent:#74a0f7; --accent-soft:#1b2436;
  --code-bg:#1a1c20;
  --danger:#f28b80; --danger-bg:#2a1c1b;
  --tip:#6bc99a; --tip-bg:#14231f;
  --info:#74a0f7;   --info-bg:#171f2e;
  --shadow:0 1px 2px rgba(0,0,0,.3),0 4px 14px rgba(0,0,0,.24);
"""

CSS = """
*,*::before,*::after{box-sizing:border-box}
:root{
  --bg:#fdfdfc; --bg-2:#f5f5f3; --bg-3:#ebebe7;
  --text:#1b1c1f; --text-2:#5b5e65; --text-3:#8a8e95;
  --border:#e3e3df; --border-strong:#cecec8;
  --accent:#2f6feb; --accent-soft:#eaf1fe;
  --code-bg:#f8f8f6;
  --danger:#c4342b; --danger-bg:#fdf1f0;
  --tip:#177f50; --tip-bg:#eff8f3;
  --info:#2f6feb;   --info-bg:#eff4fe;
  --shadow:0 1px 2px rgba(20,20,20,.05),0 4px 12px rgba(20,20,20,.04);
  --mono:ui-monospace,"SF Mono","JetBrains Mono","Cascadia Code",Menlo,Consolas,monospace;
  --sans:system-ui,-apple-system,"Segoe UI",Inter,Roboto,"Helvetica Neue",sans-serif;
  --menu:290px; --toc:15.5rem; --text-wide:52rem;
}
/* DARK BY DEFAULT: the light palette above is only the base, the dark
   s'applique sauf si le lecteur a explicitement choisi le light via la bascule.
   So we do NOT listen to prefers-color-scheme — that is a deliberate choice. */
:root:not([data-theme="light"]){__DARK__}
html{scroll-behavior:smooth;-webkit-text-size-adjust:100%}
body{margin:0;background:var(--bg);color:var(--text);font:16px/1.7 var(--sans);
  -webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
a{color:var(--accent);text-decoration:none}
a:hover{text-decoration:underline;text-underline-offset:3px}
:focus-visible{outline:2px solid var(--accent);outline-offset:2px;border-radius:4px}

/* ---------- structure ----------
   The TOC is a REAL grid column (not a `fixed` element compensated by a margin):
   otherwise, reserving its space with `margin-right` overrides the content's
   `margin:0 auto`, and the remaining `margin-left:auto` shifts all the text to the
   right on large screens. */
.wrapper{display:grid;grid-template-columns:var(--menu) minmax(0,1fr);
  min-height:100vh;align-items:start}
.menu{position:sticky;top:0;height:100vh;overflow-y:auto;background:var(--bg-2);
  border-right:1px solid var(--border);padding:1.4rem 0 3rem;scrollbar-width:thin}
/* `width:100%` is INDISPENSABLE together with `margin-inline:auto`: auto margins on a
   grid item disable stretching on the track, the item is then sized as fit-content —
   hence capped at its `max-width` (941px) whatever the track's real width. Below a
   941px viewport it overflowed to the right,
   with a global horizontal scroll. With `width:100%` it follows the track, and the
   auto margins only re-centre when there is room left. */
.content{min-width:0;width:100%;padding:2.4rem clamp(1.2rem,4vw,3.4rem) 6rem;
  max-width:calc(var(--text-wide) + 6.8rem);margin-inline:auto}

/* ---------- menu ---------- */
/* Marque en COLONNE : le badge dépôt sur sa propre ligne. Posé en bout de la
   title line, it shrank it enough to break "Vagrant-KubeADM" and
   l'horodatage en deux (menu à 290px). */
.brand{display:flex;flex-direction:column;align-items:flex-start;gap:.6rem;
  padding:0 1.3rem 1.1rem;font-weight:650;letter-spacing:-.01em}
.brand-title{display:flex;align-items:center;gap:.65rem}
.brand .logo{font-size:1.5rem;line-height:1}
.brand small{display:block;font-weight:450;color:var(--text-3);font-size:.74rem;
  letter-spacing:0;font-family:var(--mono)}
/* Repo badge, at the top of the left menu under the title.
   `currentColor` on the SVG => it follows the light/dark theme. */
.brand .repo{display:inline-flex;align-items:center;gap:.3rem;align-self:center;
  padding:.2rem .45rem;border:1px solid var(--border-strong);border-radius:6px;
  color:var(--text-2);font-size:.72rem;font-weight:600;letter-spacing:0}
.brand .repo:hover{color:var(--text);background:var(--bg-3);
  border-color:var(--text-3);text-decoration:none}
.brand .repo svg{flex:0 0 14px;width:14px;height:14px;fill:currentColor}
.search{padding:0 1.1rem 1rem}
.search input{width:100%;padding:.5rem .7rem;border:1px solid var(--border-strong);
  border-radius:8px;background:var(--bg);color:var(--text);font:inherit;font-size:.87rem}
.group > h2{margin:0;padding:.85rem 1.35rem .35rem;font-size:.69rem;font-weight:650;
  text-transform:uppercase;letter-spacing:.09em;color:var(--text-3)}
.menu a{display:flex;gap:.55rem;align-items:baseline;padding:.34rem 1.35rem;
  color:var(--text-2);font-size:.89rem;border-left:2px solid transparent}
.menu a:hover{color:var(--text);background:var(--bg-3);text-decoration:none}
.menu a.actif{color:var(--accent);background:var(--accent-soft);
  border-left-color:var(--accent);font-weight:550}
.menu a .emo{flex:0 0 1.15rem;font-size:.95rem}
.menu a .txt{min-width:0}
.menu a .path{display:block;font-size:.7rem;color:var(--text-3);
  font-family:var(--mono);word-break:break-all;line-height:1.35}
.badge{display:inline-block;margin-left:.35rem;padding:0 .34rem;border-radius:4px;
  background:var(--danger-bg);color:var(--danger);font-size:.63rem;font-weight:650;
  text-transform:uppercase;letter-spacing:.04em;vertical-align:middle}
.badge-lang{background:var(--info-bg);color:var(--info)}

/* ---------- language selector ---------- */
.languages{display:flex;gap:.3rem;padding:0 1.1rem 1rem}
.languages button{flex:1;padding:.32rem 0;border:1px solid var(--border-strong);border-radius:7px;
  background:var(--bg);color:var(--text-2);font:650 .74rem/1.45 var(--sans);
  letter-spacing:.05em;cursor:pointer;transition:color .12s,border-color .12s}
.languages button:hover{color:var(--accent);border-color:var(--accent)}
/* Theme selector: same template as .languages, right below it. */
.themes{display:flex;gap:.3rem;padding:0 1.1rem .9rem}
.themes button{flex:1;padding:.32rem 0;border:1px solid var(--border-strong);border-radius:7px;
  background:var(--bg);color:var(--text-2);font-size:.78rem;cursor:pointer}
.themes button:hover{color:var(--accent);border-color:var(--accent)}
.themes button[aria-pressed="true"]{background:var(--accent-soft);color:var(--accent);
  border-color:var(--accent)}
.languages button[aria-pressed="true"]{background:var(--accent-soft);color:var(--accent);
  border-color:var(--accent)}

/* ---------- page header ---------- */
.crumb{display:flex;align-items:center;gap:.45rem;flex-wrap:wrap;margin-bottom:.55rem;
  font:.77rem/1.5 var(--mono);color:var(--text-3)}
.page > h1{margin:.1rem 0 .35rem;font-size:clamp(1.7rem,3.4vw,2.3rem);line-height:1.18;
  letter-spacing:-.022em;font-weight:680}
.page > h1 .emo{margin-right:.45rem}
/* `code` inside a heading: kept monospace but without the inline-code frame,
   which would weigh down a 2rem heading. */
.page > h1 code{font-size:.86em;font-weight:640;background:var(--bg-3);
  border:1px solid var(--border);border-radius:7px;padding:.06em .3em}
.page h2 code,.page h3 code,.page h4 code{font-size:.9em;font-weight:inherit}
.subtitle{margin:0 0 2.2rem;color:var(--text-2);font-size:1.02rem;max-width:44rem}
.subtitle > p{margin:0 0 .4rem}

/* ---------- content ---------- */
.page h2,.page h3,.page h4{letter-spacing:-.015em;line-height:1.3;scroll-margin-top:1.5rem}
.page h2{margin:2.9rem 0 .9rem;padding-bottom:.42rem;font-size:1.4rem;font-weight:660;
  border-bottom:1px solid var(--border)}
.page h3{margin:2.1rem 0 .7rem;font-size:1.12rem;font-weight:640}
.page h4{margin:1.6rem 0 .5rem;font-size:1rem;font-weight:640;color:var(--text-2)}
.page p{margin:0 0 1.05rem}
.page ul,.page ol{margin:0 0 1.1rem;padding-left:1.4rem}
.page li{margin:.28rem 0}
.page li > p{margin:.3rem 0}
.page li::marker{color:var(--text-3)}
.page hr{margin:2.6rem 0;border:0;border-top:1px solid var(--border)}
.page strong{font-weight:640;color:var(--text)}
.page img{max-width:100%;height:auto}
.header-anchor{margin-left:.4rem;color:var(--text-3);opacity:0;font-weight:400;
  text-decoration:none;transition:opacity .12s}
h2:hover>.header-anchor,h3:hover>.header-anchor,h4:hover>.header-anchor{opacity:1}

/* ---------- code ---------- */
code{font-family:var(--mono);font-size:.875em}
:not(pre) > code{background:var(--bg-3);color:var(--text);padding:.12em .38em;
  border-radius:5px;border:1px solid var(--border)}
.code-block{position:relative;margin:0 0 1.25rem;background:var(--code-bg);
  border:1px solid var(--border);border-radius:10px;box-shadow:var(--shadow);overflow:hidden}
.code-block::before{content:attr(data-language);position:absolute;top:0;right:0;
  padding:.18rem .6rem;font:600 .65rem/1.5 var(--mono);letter-spacing:.06em;
  text-transform:uppercase;color:var(--text-3);background:var(--bg-3);
  border-left:1px solid var(--border);border-bottom:1px solid var(--border);
  border-bottom-left-radius:8px}
.code-block pre{margin:0;padding:1.55rem 1.05rem 1.05rem;overflow-x:auto;
  font-family:var(--mono);font-size:.845rem;line-height:1.62;tab-size:2}
.code-block code{white-space:pre}
.copy-btn{position:absolute;top:2.35rem;right:.55rem;z-index:2;padding:.26rem .55rem;
  border:1px solid var(--border-strong);border-radius:6px;background:var(--bg);
  color:var(--text-2);font:550 .72rem/1 var(--sans);cursor:pointer;opacity:0;
  transition:opacity .13s,color .13s}
.code-block:hover .copy-btn,.copy-btn:focus-visible{opacity:1}
.copy-btn:hover{color:var(--accent);border-color:var(--accent)}
.copy-btn.ok{color:var(--tip);border-color:var(--tip)}

/* ---------- encarts (citations) ---------- */
.callout{margin:0 0 1.25rem;padding:.85rem 1.1rem;border-left:3px solid var(--border-strong);
  border-radius:0 8px 8px 0;background:var(--bg-2);color:var(--text-2)}
.callout > :last-child{margin-bottom:0}
.callout .code-block{margin:.75rem 0 .35rem;box-shadow:none}
.callout-danger{border-left-color:var(--danger);background:var(--danger-bg)}
.callout-tip{border-left-color:var(--tip);background:var(--tip-bg)}
.callout-info{border-left-color:var(--info);background:var(--info-bg)}

/* ---------- tableaux ---------- */
.table-scroll{overflow-x:auto;margin:0 0 1.3rem;border:1px solid var(--border);
  border-radius:10px;box-shadow:var(--shadow)}
table{width:100%;border-collapse:collapse;font-size:.895rem}
th,td{padding:.58rem .85rem;text-align:left;vertical-align:top;
  border-bottom:1px solid var(--border)}
th{background:var(--bg-2);font-weight:640;font-size:.78rem;text-transform:uppercase;
  letter-spacing:.05em;color:var(--text-2);white-space:nowrap}
tbody tr:last-child td{border-bottom:0}
tbody tr:hover{background:var(--bg-2)}

/* ---------- details ---------- */
details{margin:0 0 1.3rem;border:1px solid var(--border);border-radius:10px;
  background:var(--bg-2);overflow:hidden}
details > summary{padding:.75rem 1.05rem;font-weight:600;cursor:pointer;list-style:none;
  display:flex;align-items:center;gap:.5rem}
details > summary::-webkit-details-marker{display:none}
details > summary::before{content:"›";display:inline-block;font-size:1.15rem;
  color:var(--text-3);transition:transform .15s}
details[open] > summary::before{transform:rotate(90deg)}
details > summary:hover{background:var(--bg-3)}
details > :not(summary){margin-left:1.05rem;margin-right:1.05rem}
details > :not(summary):last-child{margin-bottom:1.05rem}

/* ---------- toc de droite ---------- */
.toc{display:none;position:sticky;top:2.4rem;max-height:calc(100vh - 5rem);
  overflow-y:auto;padding:0 1.4rem 2rem 0;font-size:.82rem}
.toc h2{margin:0 0 .5rem;font-size:.69rem;font-weight:650;text-transform:uppercase;
  letter-spacing:.09em;color:var(--text-3)}
.toc a{display:block;padding:.18rem 0 .18rem .7rem;color:var(--text-2);
  border-left:2px solid var(--border);line-height:1.45}
.toc a:hover{color:var(--text);text-decoration:none}
.toc a.actif{color:var(--accent);border-left-color:var(--accent);font-weight:550}
.toc a.n3{padding-left:1.5rem;font-size:.78rem}
@media (min-width:1500px){
  .wrapper{grid-template-columns:var(--menu) minmax(0,1fr) var(--toc)}
  .toc{display:block}
}

/* ---------- topbar mobile ---------- */
.topbar{display:none;position:sticky;top:0;z-index:20;align-items:center;gap:.7rem;
  padding:.6rem .9rem;background:var(--bg);border-bottom:1px solid var(--border)}
.topbar .languages{padding:0;margin-left:auto;gap:.25rem}
.topbar .languages button{padding:.3rem .45rem;min-width:2.3rem}
.icon-button{display:grid;place-items:center;width:2.1rem;height:2.1rem;flex:0 0 auto;
  border:1px solid var(--border-strong);border-radius:8px;background:var(--bg);
  color:var(--text-2);font-size:1rem;cursor:pointer}
.icon-button:hover{color:var(--accent);border-color:var(--accent)}
.theme-floating{position:fixed;bottom:1.1rem;right:1.1rem;z-index:30;box-shadow:var(--shadow)}
.overlay{position:fixed;inset:0;z-index:35;background:rgba(0,0,0,.45);display:none}
@media (max-width:1000px){
  /* minmax(0,1fr) and NOT 1fr: a `1fr` track keeps an implicit min-width:auto,
     so it refuses to go below the intrinsic width of its content. Code blocks and
     wide tables then widened the column beyond the viewport => all the text overflowed
     to the right, with a global horizontal scroll. Desktop already used minmax(0,1fr);
     only mobile had been forgotten. */
  .wrapper{grid-template-columns:minmax(0,1fr)}
  .topbar{display:flex}
  .menu{position:fixed;inset:0 auto 0 0;width:min(86vw,var(--menu));z-index:40;
    transform:translateX(-100%);transition:transform .2s ease;box-shadow:var(--shadow)}
  .menu.ouvert{transform:none}
  .overlay.ouvert{display:block}
  .content{padding:1.6rem 1.15rem 5rem}
  .theme-floating{display:none}
}
@media print{
  .menu,.toc,.topbar,.copy-btn,.theme-floating,.header-anchor,.overlay,
  .languages,.themes{display:none!important}
  .wrapper{grid-template-columns:minmax(0,1fr)}
  .page{display:block!important;page-break-after:always}
  .code-block,.table-scroll{box-shadow:none}
}
.page{display:none}
.page.visible{display:block}
.footer{margin-top:4rem;padding-top:1.3rem;border-top:1px solid var(--border);
  color:var(--text-3);font-size:.79rem;display:flex;justify-content:space-between;
  gap:1rem;flex-wrap:wrap}
""".replace("__DARK__", DARK_PALETTE)


JS = r"""
(() => {
  const LANGUAGES = __LANGUAGES__;
  const LABELS = __LABELS__;
  const DEFAULT_LANG = __DEFAULT_LANG__;
  /* Application layer: same route format as this page, so the link can carry the language. */
  const PLATFORM_URL = __PLATFORM_URL__;
  const PLATFORM_HOME = __PLATFORM_HOME__;

  const pages = [...document.querySelectorAll('.page')];
  const links = [...document.querySelectorAll('.menu a[data-page]')];
  const menu  = document.querySelector('.menu');
  const overlay = document.querySelector('.overlay');
  const box = document.querySelector('.toc');
  const field = document.querySelector('.search input');
  let observer = null;

  /* --- language: remembered, but always derived from the displayed page --- */
  const LANG_KEY = 'kubeadm-doc-lang';
  const storedLang = localStorage.getItem(LANG_KEY);
  let lang = LANGUAGES.includes(storedLang) ? storedLang : DEFAULT_LANG;
  const words = () => LABELS[lang];

  const updateLang = (nextEntry) => {
    lang = nextEntry;
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
    const m = words();
    document.querySelectorAll('.tree').forEach(a => { a.hidden = a.dataset.lang !== lang; });
    document.querySelectorAll('.languages button').forEach(b => {
      b.setAttribute('aria-pressed', String(b.dataset.lang === lang));
    });
    field.placeholder = m.search;
    field.setAttribute('aria-label', m.search_aria);
    document.querySelectorAll('[data-menu-toggle]').forEach(b => b.setAttribute('aria-label', m.menu));
    document.querySelectorAll('.languages').forEach(g => g.setAttribute('aria-label', m.lang_aria));
    document.querySelectorAll('[data-repo]').forEach(a => {
      a.setAttribute('aria-label', m.repo); a.setAttribute('title', m.repo);
    });
    document.querySelectorAll('[data-platform]').forEach(a => {
      a.setAttribute('aria-label', m.platform); a.setAttribute('title', m.platform);
      a.href = PLATFORM_URL + '#' + lang + '/' + PLATFORM_HOME;
      const s = a.querySelector('span'); if (s) s.textContent = m.platform_short;
    });
    document.querySelectorAll('.copy-btn').forEach(b => { b.textContent = m.copy; });
    updateTheme();
    if (box.firstElementChild) box.firstElementChild.textContent = m.toc;
  };

  /* --- TOC of the displayed page + highlight while reading --- */
  const buildToc = (page) => {
    const headings = [...page.querySelectorAll('h2[id],h3[id]')];
    observer?.disconnect();
    if (headings.length < 3) { box.innerHTML = ''; return; }
    box.innerHTML = `<h2>${words().toc}</h2>` + headings.map(h => {
      const label_text = h.textContent.replace(/#$/, '').trim();
      return `<a href="#${page.id}/${h.id}" data-lang-for="${h.id}"
                 class="${h.tagName === 'H3' ? 'n3' : ''}">${label_text}</a>`;
    }).join('');
    const anchors = new Map([...boite.querySelectorAll('a')].map(a => [a.dataset.langFor, a]));
    observer = new IntersectionObserver(entries => {
      for (const e of entries) {
        if (!e.isIntersecting) continue;
        anchors.forEach(a => a.classList.remove('active'));
        anchors.get(e.target.id)?.classList.add('active');
      }
    }, { rootMargin: '-8% 0px -80% 0px' });
    headings.forEach(h => observer.observe(h));
  };

  /* --- routage : #<lang>/<page>/<section> ---
     The old format (#<page>/<section>, without a language) is still accepted: links
     already shared keep opening the right page, in the current language. */
  const show = (id, section) => {
    const target = pages.find(p => p.id === id)
               ?? pages.find(p => p.dataset.lang === lang)
               ?? pages[0];
    if (target.dataset.lang !== lang) updateLang(target.dataset.lang);
    pages.forEach(p => p.classList.toggle('visible', p === target));
    links.forEach(a => {
      const active = a.dataset.page === target.id;
      a.classList.toggle('active', active);
      active ? a.setAttribute('aria-current', 'page') : a.removeAttribute('aria-current');
    });
    buildToc(target);
    document.title = target.dataset.title + ' · Vagrant-KubeADM';
    const h = section && target.querySelector('[id="' + CSS.escape(section) + '"]');
    h ? h.scrollIntoView() : window.scrollTo(0, 0);
  };
  const route = () => {
    const parts = decodeURIComponent(location.hash.slice(1)).split('/').filter(Boolean);
    return LANGUAGES.includes(parts[0])
      ? { id: parts.slice(0, 2).join('/'), section: parts[2] }
      : { id: parts.length ? lang + '/' + parts[0] : '', section: parts[1] };
  };
  const router = () => { const r = route(); show(r.id, r.section); };

  /* --- language switch: same page, other version --- */
  document.querySelectorAll('.languages button').forEach(b => b.addEventListener('click', () => {
    const nextEntry = b.dataset.lang;
    if (nextEntry === lang) return;
    const current = pages.find(p => p.classList.contains('visible'));
    const section = route().section;
    updateLang(nextEntry);
    location.hash = '#' + nextEntry + '/' + (current?.dataset.doc ?? '')
                  + (section ? '/' + section : '');
    router();   /* when the hash did not change (missing page), render anyway */
  }));

  /* --- search (title, path, sections); "/" focuses the field --- */
  field.addEventListener('input', () => {
    const q = field.value.trim().toLowerCase();
    links.forEach(a => { a.hidden = !!q && !a.dataset.search.includes(q); });
    document.querySelectorAll('.group').forEach(g => {
      g.hidden = ![...g.querySelectorAll('a')].some(a => !a.hidden);
    });
  });
  document.addEventListener('keydown', e => {
    if (e.key === '/' && document.activeElement !== field) { e.preventDefault(); field.focus(); }
    else if (e.key === 'Escape' && document.activeElement === field) {
      field.value = ''; field.dispatchEvent(new Event('input')); field.blur();
    }
  });

  /* --- copy a code block --- */
  document.addEventListener('click', async e => {
    const b = e.target.closest('.copy-btn');
    if (!b) return;
    const m = words();
    try {
      await navigator.clipboard.writeText(b.parentElement.querySelector('code').innerText);
      b.textContent = m.copied; b.classList.add('ok');
    } catch { b.textContent = m.failed; }
    setTimeout(() => { b.textContent = words().copy; b.classList.remove('ok'); }, 1600);
  });

  /* --- theme: DARK by default, remembered toggle --- */
  const KEY = 'kubeadm-doc-theme';
  const stored = localStorage.getItem(KEY);
  if (stored) document.documentElement.dataset.theme = stored;
  function updateTheme() {
    const dark = (document.documentElement.dataset.theme || 'dark') === 'dark';
    const m = words();
    document.querySelectorAll('[data-theme-toggle]').forEach(b => {
      b.textContent = dark ? '☀' : '☾';
      b.title = dark ? m.to_light : m.to_dark;
      b.setAttribute('aria-label', b.title);
    });
    /* Segmented group of the side bar: state + labels (which follow the language). */
    document.querySelectorAll('.themes button').forEach(b => {
      const active = b.dataset.themeSet === (dark ? 'dark' : 'light');
      b.setAttribute('aria-pressed', String(active));
      b.textContent = (b.dataset.themeSet === 'dark' ? '☾ ' : '☀ ')
                    + (b.dataset.themeSet === 'dark' ? m.theme_dark : m.theme_light);
    });
    document.querySelectorAll('.themes').forEach(g => g.setAttribute('aria-label', m.theme_aria));
  }
  document.querySelectorAll('.themes button').forEach(b => b.addEventListener('click', () => {
    document.documentElement.dataset.theme = b.dataset.themeSet;
    localStorage.setItem(KEY, b.dataset.themeSet);
    updateTheme();
  }));
  document.querySelectorAll('[data-theme-toggle]').forEach(b => b.addEventListener('click', () => {
    const next_ = (document.documentElement.dataset.theme || 'dark') === 'dark' ? 'light' : 'dark';
    document.documentElement.dataset.theme = next_;
    localStorage.setItem(KEY, next_);
    updateTheme();
  }));

  /* --- menu mobile --- */
  const toggle = ouvrir => {
    menu.classList.toggle('ouvert', ouvrir);
    overlay.classList.toggle('ouvert', ouvrir);
  };
  document.querySelector('[data-menu-toggle]').addEventListener('click',
    () => toggle(!menu.classList.contains('ouvert')));
  overlay.addEventListener('click', () => toggle(false));
  links.forEach(a => a.addEventListener('click', () => toggle(false)));

  addEventListener('hashchange', router);
  updateLang(lang);
  router();
})();
"""


# ===========================================================================
#  Assembly
# ===========================================================================

def language_selector(words: dict[str, str]) -> str:
    """EN/FR buttons. Rendered twice (side bar and mobile bar)."""
    buttons = "".join(
        f'<button type="button" data-lang="{l}" aria-pressed="false">{l.upper()}</button>'
        for l in LANGUAGES
    )
    return (f'<div class="languages" role="group" '
            f'aria-label="{html.escape(words["lang_aria"], quote=True)}">{buttons}</div>')


def theme_selector(words: dict[str, str]) -> str:
    """EXPLICIT light/dark selector, placed in the side bar.

    Two `data-theme-toggle` switches already existed: one in the mobile bar, one
    floating at the bottom right. But the mobile bar is `display:none` on a desktop, so
    the only control visible there was an unlabelled ☀ pill, in a corner, on top of the
    content — invisible in practice.

    So we add a segmented "Light / Dark" group modelled on the language selector, in the
    same place and with the same shape: that is where the eye looks for it.
    The two original switches stay in place and share the state.
    """
    buttons = "".join(
        f'<button type="button" data-theme-set="{value}" aria-pressed="false">'
        f'{icon} {html.escape(words[key_label])}</button>'
        for value, icon, key_label in (("light", "☀", "theme_light"), ("dark", "☾", "theme_dark"))
    )
    return (f'<div class="themes" role="group" '
            f'aria-label="{html.escape(words["theme_aria"], quote=True)}">{buttons}</div>')


# Official GitHub mark (viewBox 16x16, single path). Inline because the page must
# stay self-contained: no network request on load.
SVG_GITHUB = (
    '<svg viewBox="0 0 16 16" aria-hidden="true" focusable="false"><path d="M8 0C3.58 0 '
    '0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01'
    '.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 '
    '1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87'
    '.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36'
    '.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 '
    '3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55'
    '.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/></svg>'
)


def repo_link(words: dict[str, str]) -> str:
    """The "GitHub" badge of the brand line, at the top of the left menu.

    The visible label stays "GitHub" in both languages (it is a proper name); only the
    accessible label is translated, and the JS refreshes it
    au changement de lang (cf. updateLang).
    """
    heading = html.escape(words["repo"], quote=True)
    return (f'<a class="repo" href="{REPO_URL}" target="_blank" rel="noopener noreferrer"'
            f' data-repo title="{heading}" aria-label="{heading}">{SVG_GITHUB}'
            f'<span>GitHub</span></a>')


def platform_link(words: dict[str, str], lang: str) -> str:
    """Link to the application layer's documentation, outside this repository.

    `_k8s/` is a submodule pointing at k8s-playground, shared with the Talos lab.
    Its documentation is published by that repo; we do not duplicate it here, we link to it.
    The link is EXTERNAL: it opens a new tab, like the GitHub badge.

    The href carries the language (`#fr/readme`), and the JS rewrites it on every language
    switch — the target site reads that route and opens in the same language. What is
    rendered here is the no-JS fallback, in the page's default language.
    """
    heading = html.escape(words["platform"], quote=True)
    return (f'<a class="repo" href="{platform_href(lang)}" target="_blank" rel="noopener noreferrer"'
            f' data-platform title="{heading}" aria-label="{heading}">☸️'
            f'<span>{html.escape(words["platform_short"])}</span></a>')


def render(docs: list[dict]) -> list[dict]:
    """Renders every document in every language (one entry per HTML page)."""
    md = create_converter()
    rendered_pages: list[dict] = []
    for doc in docs:
        for lang in LANGUAGES:
            path = doc["paths"][lang]
            page = {
                "path": path,
                "emoji": doc["emoji"],
                "text": read_file(path),
                "id": f"{lang}/{doc['id']}",
            }
            r = convert(md, page)
            rendered_pages.append({
                **r,
                "id": page["id"],
                "doc": doc["id"],
                "lang": lang,
                "path": path,
                "group": doc["group"][lang],
                "tracked": doc["tracked"],
                # a document without a mirror shows in English inside the French menu;
                # the ones in WITHOUT_MIRROR own that and carry no badge
                "translated": (doc["paths"]["en"] != doc["paths"]["fr"]
                            or lang == "en" or doc["path"] in WITHOUT_MIRROR),
            })
    return rendered_pages


def build_page(rendered_pages: list[dict], version: str, warnings: list[str]) -> str:
    # path → route index, per language: the links of a French page target the French
    # mirrors; the English path is the fallback (untranslated page).
    index: dict[str, dict[str, str]] = {l: {} for l in LANGUAGES}
    anchors: dict[str, set[str]] = {}
    for r in rendered_pages:
        index[r["lang"]][r["path"]] = r["id"]
        anchors[r["id"]] = set(RE_HEADING_ID.findall(r["body"]))
    for r in rendered_pages:
        index[r["lang"]].setdefault(
            next(x["path"] for x in rendered_pages
                 if x["doc"] == r["doc"] and x["lang"] == "en"), r["id"])

    articles: list[str] = []
    menus: dict[str, dict[str, list[str]]] = {l: {} for l in LANGUAGES}

    for r in rendered_pages:
        words = LABELS[r["lang"]]
        body = inline_images(resolve(r, index, anchors, warnings),
                               r["path"], warnings)
        badges = ""
        if not r["tracked"]:
            badges += (f'<span class="badge" title="{html.escape(words["badge_title"], quote=True)}">'
                       f'{html.escape(words["badge"])}</span>')
        if not r["translated"]:
            badges += (f'<span class="badge badge-lang" '
                       f'title="{html.escape(words["badge_lang_title"], quote=True)}">'
                       f'{html.escape(words["badge_lang"])}</span>')

        # first callout promoted to the lead under the title (the neutralised H1 leaves
        # blanks at the start: hence the lstrip before matching)
        lead = ""
        body = body.lstrip()
        m = re.match(r'<blockquote class="callout[^"]*">(.*?)</blockquote>\s*', body, re.DOTALL)
        if m:
            lead, body = m.group(1), body[m.end():]

        articles.append(
            f'<article class="page" id="{r["id"]}" data-doc="{r["doc"]}" '
            f'data-lang="{r["lang"]}" '
            f'data-title="{html.escape(r["title_text"], quote=True)}">'
            f'<div class="crumb"><span>{html.escape(r["path"])}</span>{badges}</div>'
            f'<h1><span class="emo">{r["emoji"]}</span>{r["title_html"]}</h1>'
            f'{f"""<div class="subtitle">{lead}</div>""" if lead else ""}'
            f'{body}'
            f'<div class="footer">'
            f'<span>{html.escape(words["source"])} <code>{html.escape(r["path"])}</code></span>'
            f'<span>{len(r["toc"])} {html.escape(words["sections"])}</span></div>'
            "</article>"
        )

        search = html.escape(" ".join(
            [r["title_text"], r["path"], *(s["title"] for s in r["toc"])]).lower(),
            quote=True)
        menus[r["lang"]].setdefault(r["group"], []).append(
            f'<a href="#{r["id"]}" data-page="{r["id"]}" data-search="{search}">'
            f'<span class="emo">{r["emoji"]}</span>'
            f'<span class="txt">{html.escape(r["title_text"])}{badges}'
            f'<span class="path">{html.escape(r["path"])}</span></span></a>'
        )

    trees = []
    for lang in LANGUAGES:
        order = [g[0][lang] for g in GROUPS] + [OTHER[lang]]
        nav = "".join(
            f'<nav class="group"><h2>{html.escape(g)}</h2>{"".join(menus[lang][g])}</nav>'
            for g in order if g in menus[lang]
        )
        trees.append(f'<div class="tree" data-lang="{lang}" hidden>{nav}</div>')

    words = LABELS[DEFAULT_LANGUAGE]
    js = (JS.replace("__LANGUAGES__", json.dumps(list(LANGUAGES)))
            .replace("__LABELS__", json.dumps(LABELS, ensure_ascii=False))
            .replace("__DEFAULT_LANG__", json.dumps(DEFAULT_LANGUAGE))
            .replace("__PLATFORM_URL__", json.dumps(PLATFORM_URL))
            .replace("__PLATFORM_HOME__", json.dumps(PLATFORM_HOME)))

    return f"""<!doctype html>
<html lang="{DEFAULT_LANGUAGE}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="dark light">
<meta name="generator" content="docs/build.py">
<meta name="description" content="{html.escape(words['subtitle'], quote=True)}">
<title>Vagrant-KubeADM · Documentation</title>
<style>
{CSS}
{css_pygments()}
</style>
</head>
<body>
<div class="overlay"></div>
<header class="topbar">
  <button class="icon-button" data-menu-toggle aria-label="{html.escape(words['menu'], quote=True)}">☰</button>
  <strong>Vagrant-KubeADM</strong>
  {language_selector(words)}
  <button class="icon-button" data-theme-toggle>☀</button>
</header>
<div class="wrapper">
  <aside class="menu">
    <div class="brand">
      <div class="brand-title">
        <span class="logo">🐧</span>
        <span>Vagrant-KubeADM<small>{html.escape(version)}</small></span>
      </div>
      {repo_link(words)}
      {platform_link(words, DEFAULT_LANGUAGE)}
    </div>
    {language_selector(words)}
    {theme_selector(words)}
    <div class="search">
      <input type="search" placeholder="{html.escape(words['search'], quote=True)}"
             aria-label="{html.escape(words['search_aria'], quote=True)}">
    </div>
    {"".join(trees)}
  </aside>
  <main class="content">{"".join(articles)}</main>
  <aside class="toc" aria-label="{html.escape(words['toc'], quote=True)}"></aside>
</div>
<button class="icon-button theme-floating" data-theme-toggle>☀</button>
<script>{js}</script>
</body>
</html>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Generates the lab's HTML documentation.")
    ap.add_argument("--out", default=str(ROOT / "docs" / "index.html"),
                    help="output file (default: docs/index.html)")
    ap.add_argument("--strict", action="store_true",
                    help="fail when an internal link or anchor does not resolve")
    args = ap.parse_args()

    docs = discover()
    if not docs:
        print("No markdown file found.", file=sys.stderr)
        return 1
    for doc in docs:  # identifiant de route, stable et lisible
        doc["id"] = re.sub(r"[^a-z0-9]+", "-",
                           doc["path"].lower().removesuffix(".md")).strip("-")

    warnings: list[str] = []
    rendered_pages = render(docs)
    output = Path(args.out)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        build_page(rendered_pages, git("log", "-1", "--format=%h · %cs") or "local", warnings),
        encoding="utf-8")

    display = output.relative_to(ROOT) if output.is_relative_to(ROOT) else output
    print(f"✅ {display} — {len(docs)} documents × {len(LANGUAGES)} languages "
          f"= {len(rendered_pages)} pages, {output.stat().st_size // 1024} Ko")
    for doc in docs:
        state = "" if doc["tracked"] else "  (untracked)"
        mirror = doc["paths"]["fr"]
        if mirror == doc["path"]:
            # tell an oversight (to fix) from a deliberate choice (WITHOUT_MIRROR)
            state += ("  (EN only, by design)" if doc["path"] in WITHOUT_MIRROR
                     else "  (⚠️ no FR mirror)")
            mirror = "—"
        print(f"   {doc['emoji']} {doc['path']:44s} ↔ {mirror}{state}")

    if warnings:
        print(f"\n⚠️ {len(warnings)} unresolved internal link(s):", file=sys.stderr)
        for a in sorted(set(warnings)):
            print(f"   {a}", file=sys.stderr)
        if args.strict:
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
